from django.urls import path
from . import views
from .chat import chat_view, chat_stream_view
from .conversations import (
    conversations_list_view,
    conversation_detail_view,
    conversation_delete_view,
    conversation_message_view,
    conversation_share_view,
    public_share_view,
)

urlpatterns = [
    path('health/', views.health_view, name='health'),
    path('file-upload/', views.file_upload, name='file-upload'),
    path('check/<str:job_id>/', views.check_job_status, name='check-job-status'),
    path('chat/', chat_view, name='chat'),
    path('chat/stream/', chat_stream_view, name='chat-stream'),
    path('conversations/', conversations_list_view, name='conversations-list'),
    path('conversations/<str:conversation_id>/', conversation_detail_view, name='conversation-detail'),
    path('conversations/<str:conversation_id>/delete/', conversation_delete_view, name='conversation-delete'),
    path('conversations/<str:conversation_id>/messages/', conversation_message_view, name='conversation-messages'),
    path('conversations/<str:conversation_id>/share/', conversation_share_view, name='conversation-share'),
    path('share/<str:token>/', public_share_view, name='public-share'),
    path('datasets/', views.list_datasets_view, name='list-datasets'),
    path('datasets/<str:dataset_id>/', views.delete_dataset_view, name='delete-dataset'),
    path('datasets/<str:dataset_id>/dashboard/', views.get_dataset_dashboard_view, name='dataset-dashboard'),
    path('datasets/<str:dataset_id>/aggregate/', views.aggregate_charts_view, name='dataset-aggregate'),
    path('datasets/<str:dataset_id>/customize-chart/', views.customize_chart_view, name='dataset-customize-chart'),
    path('datasets/<str:dataset_id>/rows/', views.get_dataset_rows_view, name='dataset-rows'),
    path('datasets/<str:dataset_id>/forecast/', views.forecast_dataset_view, name='dataset-forecast'),
    path('datasets/<str:dataset_id>/forecasts/', views.get_forecast_history_view, name='forecast-history'),
    path('datasets/<str:dataset_id>/export-pdf/', views.export_pdf, name='export-pdf'),
    path('forecasts/status/<str:job_id>/', views.get_forecast_status_view, name='forecast-status'),
    path('forecasts/<str:forecast_id>/', views.get_forecast_detail_view, name='forecast-detail'),
    path('forecasts/<str:forecast_id>/delete/', views.delete_forecast_view, name='forecast-delete'),
    path('forecasts/<str:forecast_id>/accuracy/', views.get_forecast_accuracy_view, name='forecast-accuracy'),
    path('datasets/<str:dataset_id>/append/', views.append_to_dataset_view, name='append-to-dataset'),
    path('datasets/<str:dataset_id>/feature-recommendations/', views.get_feature_recommendations_view, name='feature-recommendations'),
    path('dashboard/stats/', views.get_kpi_stats_view, name='dashboard-stats'),
    path('process/<str:dataset_id>/', views.process_file_step_4, name='process-file-step-4'),
    path('datasets/<str:dataset_id>/segmentation/', views.run_segmentation_view, name='run-segmentation'),
    path('datasets/<str:dataset_id>/segmentation/results/', views.get_segmentation_results_view, name='segmentation-results'),
    path('datasets/<str:dataset_id>/recommendations/', views.get_recommendations_view, name='get-recommendations'),
    path('datasets/<str:dataset_id>/recommendations/generate/', views.generate_recommendations_view, name='generate-recommendations'),
    path('datasets/<str:dataset_id>/category/', views.update_dataset_category_view, name='update-dataset-category'),
    path('datasets/<str:dataset_id>/detect-category/', views.detect_dataset_category_view, name='detect-dataset-category'),
    path('model-category-stats/', views.model_category_stats_view, name='model-category-stats'),
    path('datasets/<str:dataset_id>/column-correlations/', views.column_correlations_view, name='column-correlations'),
    path('tts/', views.tts_view, name='tts'),
    path('tts/usage/', views.tts_usage_view, name='tts-usage'),
    path('translate-for-tts/', views.translate_for_tts_view, name='translate-for-tts'),
    path('datasets/<str:dataset_id>/audio-overview/', views.dataset_audio_overview_view, name='dataset-audio-overview'),
    path('voice-logs/', views.voice_logs_list_view, name='voice-logs-list'),
    path('voice-logs/clear/', views.voice_logs_clear_view, name='voice-logs-clear'),
    path('voice-logs/<str:entry_id>/', views.voice_log_delete_view, name='voice-log-delete'),
    path('voice-logs/<str:entry_id>/audio/', views.voice_log_audio_view, name='voice-log-audio'),
]
