import { useEffect, useState, lazy, Suspense } from 'react'
import { useParams } from 'react-router-dom'
import { getSharedConversation } from '../../api'
import ChatChartRenderer from './ChatChart'
import type { ChatChart, Chat3DVisual } from '../../hooks/useChat'
import { LogoSpinner } from '../ui/LogoSpinner'

const Visual3D = lazy(() => import('./Visual3D'))

interface Message {
  id: string
  role: string
  content: string
  chart_data?: ChatChart | null
  visual_3d?: Chat3DVisual | null
  created_at: string
}

interface SharedConversation {
  id: string
  title: string
  created_at: string
}

export default function SharePage() {
  const { token } = useParams<{ token: string }>()
  const [conversation, setConversation] = useState<SharedConversation | null>(null)
  const [messages, setMessages] = useState<Message[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!token) return
    getSharedConversation(token)
      .then(data => {
        setConversation(data.conversation)
        const msgs = (data.messages || []).map((m: any) => ({
          ...m,
          chart_data: typeof m.chart_data === 'string' ? JSON.parse(m.chart_data) : m.chart_data,
          visual_3d: typeof m.visual_3d === 'string' ? JSON.parse(m.visual_3d) : m.visual_3d,
        }))
        setMessages(msgs)
      })
      .catch(() => setError('This shared conversation could not be found or has been removed.'))
      .finally(() => setLoading(false))
  }, [token])

  if (loading) {
    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center">
        <LogoSpinner size={48} />
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center">
        <div className="text-center">
          <i className="fa-solid fa-link-slash text-4xl text-muted-foreground mb-4" />
          <p className="text-muted-foreground">{error}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-border px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#5A5AF6] to-[#8B5CF6] flex items-center justify-center">
              <i className="fa-solid fa-robot text-foreground text-sm" />
            </div>
            <div>
              <h1 className="text-base font-semibold">{conversation?.title || 'Shared Conversation'}</h1>
              <p className="text-xs text-muted-foreground">Shared from AxBi</p>
            </div>
          </div>
          <span className="text-xs text-muted-foreground bg-card px-2 py-1 rounded">Read-only</span>
        </div>
      </header>

      {/* Messages */}
      <div className="max-w-4xl mx-auto px-6 py-6 space-y-4">
        {messages.map((msg) => (
          <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[75%] ${msg.role !== 'user' ? 'w-full max-w-3xl' : ''}`}>
              <div className={`rounded-xl px-4 py-3 text-sm leading-relaxed ${
                msg.role === 'user'
                  ? 'bg-primary text-primary-foreground rounded-br-sm'
                  : 'bg-card text-foreground border border-border rounded-bl-sm'
              }`}>
                <div className="whitespace-pre-wrap">{msg.content}</div>
              </div>
              {msg.chart_data && <ChatChartRenderer chart={msg.chart_data} height={300} />}
              {msg.visual_3d && (
                <Suspense fallback={<div className="mt-2 h-[350px] bg-background rounded-lg border border-border flex items-center justify-center text-muted-foreground text-xs">Loading 3D...</div>}>
                  <Visual3D visual={msg.visual_3d} height={450} />
                </Suspense>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <footer className="border-t border-border px-6 py-3 text-center">
        <p className="text-xs text-muted-foreground">
          Generated by <span className="text-primary font-medium">AxBi</span> AI Assistant
        </p>
      </footer>
    </div>
  )
}
